### ISSUE TITLE
volume key presses interpreted as navigation

### ISSUE THREAD

**Issue by orazdow** [clangen/musikcube#375] opened 2020-10-27 08:43 UTC
Hi, I noticed that if the console if focused, when I use the dedicated volume keys (I'm on a Lenovo flex 14 laptop running win10), the selected regions in the gui are changing. I thought I should point that out. If there is an easy to locate region i the source where I the key events are interpreted, I could possible look at it myself, but either way I thought I should point this out.

**Comment by clangen** [comment] 2021-04-12 05:17
Sorry, I finally got access to a Lenovo (T430) laptop and gave this a try, but was unable to reproduce the issue. It's possible the bug was fixed in a release since you tested. 

Here's what I did:
1. Started musikcube, added some files
2. Started playback
3. Toggled to console view via `~`
4. Used the hardware volume keys; they seemed to adjust the OS-level volume as expected (no bug)
5. Also tested the standard volume up/down keys (`l` and `k`), and while they didn't work (the console ate the inputs as expected), nothing in the UI looked amiss.

In the off chance you're still using musikcube and having this problem with the latest version, please re-open this ticket and let me know if I missed any steps! Closing for now as part of our ongoing issue tracker cleanup.

**Closed as completed by clangen** 2021-04-12 05:17 UTC
