### ISSUE TITLE
Musikcube erroring after a few seconds.

### ISSUE THREAD

**Issue by worldpe** [clangen/musikcube#451] opened 2021-07-13 21:57 UTC
I am sorry for making an issue about this, it might be the wrong place, and it is possible the issue is just musikcube is just having some issue with reading a media file I have. I am going to post the error message and if someone knows what it means, then that would be appreciated, if not I will try something else.

`/usr/include/c++/11.1.0/bits/basic_string.h:1026: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.                      │
│Sargeist                           ││                                                                                          /usr/include/c++/11.1.0/bits/basic_string.h:1026: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.`

**Comment by clangen** [comment] 2021-07-13 23:57
Just to be clear, it crashes while indexing media files? If so, you probably have a file with seriously corrupted (or bizarre) metadata. Usually once or twice a year someone reports a file that crashes the app. If you can narrow down which file is causing the issue I can try to fix it.

To find the bad file you'll need to start a fresh install and enable a couple magic options:

1. `rm -rf ~/.config/musikcube`
2. Start `musikcube` and go to `settings` > `advanced settings`. Change:
    * `IndexerLogEnabled` to `true`
    * `IndexerThreadCount` to `1`
3. Quit and restart the app again (very important!)

![image](https://user-images.githubusercontent.com/2031666/125539911-d29855e6-fa53-46da-9a1c-5c36cab67896.png)

After this, go ahead and try to add your files again. It'll run slower this time, and it'll still crash, but it'll create a log file in the following location: `~/.config/musikcube/indexer_log.txt`

This log file should contain information that'll help you determine which file is causing issues.

**Comment by worldpe** [comment] 2021-07-14 03:39
It will load the first 301 tracks, then after the next 301 tracks, it will have a crash message. I removed the directory containing the file that was last loaded, but it persisted, I am not having this issue with other music players, and I am suspecting that maybe the last track loaded was just whatever was the 301st track indexed.

**Comment by clangen** [comment] 2021-07-14 05:07
Hmm, very interesting. The fact that it's happening at the 300-301 track boundary suggests there's something strange with committing a database transaction. 

For a little bit of background: as musikcube scans your directories for music, it writes the metadata to a local `sqlite` database in the `~/.config/musikcube` directory. By default it works in units of 300; every time it finishes scanning 300 tracks (give or take, depending on the number of threads), it commits (saves) the data to the database, and moves on to another chunk of 300.

I fear this is going to be very tricky to track down without knowing how to reproduce the issue. If you'll humor me, I'm curious if you change `IndexerThreadCount` to `1`, and then `IndexerTransactionInterval` to something like `500` if you observe the crash after scanning `500` files.

The snippet of the crash you pasted suggests some sort of string-allocation related issue. I'm curious if it has to do with some sort of character encoding issue.

Can you tell me which operating system and version you are using, and the default language and locale you have setup?

Also, would you mind giving me the output of your `env` command? I can try to setup a similar environment here. (**Note**: make sure you review the contents of `env` before posting it here and remove anything that would be considered sensitive information).

**Comment by worldpe** [comment] 2021-07-14 19:42
I set the interval to 500, and restarted the application after, but it did not seem to do anything different, meaning it still went 301 tracks at a time. 

My env output is: 
SHLVL=1
ALACRITTY_LOG=/tmp/Alacritty-48968.log
GJS_DEBUG_OUTPUT=stderr
BROWSER=firefox
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
PWD=/home/wpeace
DESKTOP_SESSION=gnome
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/Alacritty.desktop
GIO_LAUNCHED_DESKTOP_FILE_PID=48968
SESSION_MANAGER=local/endeavour:@/tmp/.ICE-unix/654,unix/endeavour:/tmp/.ICE-unix/654
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GDMSESSION=gnome
GNOME_SETUP_DISPLAY=:1
HOME=/home/wpeace
COLORTERM=truecolor
INVOCATION_ID=b4cd69b5ea584004a1a7af7fc7c88f41
LANG=en_US.UTF-8
SYSTEMD_EXEC_PID=670
XDG_DATA_DIRS=/home/wpeace/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
JOURNAL_STREAM=8:18836
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
SHELL=/bin/bash
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
MOTD_SHOWN=pam
LC_IDENTIFICATION=en_US.UTF-8
LOGNAME=wpeace
LC_MONETARY=en_US.UTF-8
MANAGERPID=604
DISPLAY=:0
LC_TIME=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.IPAC60
GDM_LANG=en_US.UTF-8
MAIL=/var/spool/mail/wpeace
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
USER=wpeace
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=gnome
XDG_CURRENT_DESKTOP=GNOME
USERNAME=wpeace
WAYLAND_DISPLAY=wayland-0
TERM=alacritty
LC_MEASUREMENT=en_US.UTF-8
XDG_SESSION_TYPE=wayland
LC_PAPER=en_US.UTF-8

I am on Endeavouros, and I have had this happen with the normal and git version of the program, I didn't have this issue previously using the same hardware and music files on the same distro, in my test just now.

**Comment by divvy96** [comment] 2021-09-14 10:57
having the same error when trying to open up the filter menu. I can add everything to the library fine when I hit filter the application crashes. I've managed to identify one of the tracks that causes the crash. Doesn't look to be anything strange about the file. Any recommendations on what to look for?

**Comment by gapys-krzysztof** [comment] 2021-12-09 14:26
I am encountering the same issue as mentioned by @divvy96 . Have tried the `~/.config/musikcube/indexer_log.txt` method, but at the end of it wasn't any problematic song looking at the tags and the filename (plus it plays fine in the library view). The songs seem to be identified properly in the [b]rowse tab, it's just the [f]ilter one that instantly crashes the app for me.

My collection does feature quite a lot of weirdly coded metadata, I believe - e.g. japanese characters in the artist/song names render as boxes in the library view.

**Comment by gapys-krzysztof** [comment] 2021-12-09 17:51
I think I got it to work while attempting to fix something else, and because of that it's hard to pinpoint what the exact solution was. I was fixing DWM/st font crash issues and replaced libxft with libxft-bgra. I also fixed Xorg's font paths by using mkfontdir in the /usr/share/fonts folder. Hope it is of some help for someone in the future.

Edit: On the offshoot chance it was the cause, I also installed noto-fonts-cjk and noto-fonts-emoji packages.

**Comment by divvy96** [comment] 2021-12-21 20:49
I've been able to narrow it down to a single song that is causing the issue for me. Bring me the horizon - The comedown. There doesn't seem to be any weird metadata on it

**Comment by clangen** [comment] 2021-12-22 18:40
@divvy96 if you can share the file with me I can try to figure out what's causing the crash

**Comment by clangen** [comment] 2022-01-03 08:53
Closing for now due to lack of correspondence.

**Closed as completed by clangen** 2022-01-03 08:53 UTC

**Comment by divvy96** [comment] 2022-03-04 11:40
github won't let me upload the file. I've tried zipping it, tar.gzip. any other way to forward the file on?

re-encoding the file appears to have stopped the crash.
when I test the file using ```flac -t FILE``` I get no errors with the file.

Inspecting the file with less shows blank but not zero length metadata for genre and comment fields.

**Comment by divvy96** [comment] 2022-03-04 17:17
so I've had another bit of a play around with the metadata in a couple of the songs that caused the crash. After rewriting the meta data for the track to ```''``` i.e. empty string for genre, replacing the whitespace character that was in the original file, the application no longer crashes.

edit: looks to be a space followed by a ```\t```
