### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by crstin** [clangen/musikcube#110] opened 2017-07-26 07:15 UTC
On macOS playback for most of my longer mp3 files (podcasts etc.) is too fast.

**Comment by osaatcioglu** [comment] 2017-07-26 08:39
I experienced the same and I can add that the duration of the mp3 player is not important. All of my mp3's are too fast. Is there a way to change the playback speed? It could be a cool feature also.

Great player btw. Thank you.

**Comment by clangen** [comment] 2017-07-27 00:15
Sounds like the bitrate isn't getting interpreted correctly. Do either of you know the bitrate of the files in question? I can try to create one here with the same rate and see if I can repro.

**Comment by crstin** [comment] 2017-07-27 01:11
@clangen yeah probably all files which have certain bitrates sound strange (or skip), just try `16kb/s` for instance or `64kb/s`. I've also other bitrates where the issue occurs.

**Comment by osaatcioglu** [comment] 2017-07-27 08:10
My files are 48k/s. Here is the detail info for one of them. 

File type ID:   MPG3
Num Tracks:     1
Data format:     1 ch,  32000 Hz, '.mp3' (0x00000000) 0 bits/channel, 0 bytes/packet, 1152 frames/packet, 0 bytes/frame
                no channel layout.
estimated duration: 325.872000 sec
audio bytes: 1955232
audio packets: 9052
bit rate: 48000 bits per second
packet size upper bound: 1448
maximum packet size: 216
audio data file offset: 26099
optimized

**Comment by clangen** [comment] 2017-07-29 18:22
OK, so, I've narrowed the problem down to our `mad`-based decoder called `nomad`, which was originally written by the `cmus` guys. 

~~This bug not only causes playback speed issues, but also seems to corrupt the processes heap in come cases, which will eventually cause the app to crash~~. 

Edit 1: heap corruption was another bug that has been latent for a long time, just exposed by files with very low sampling rates in the WASAPI output plugin.

~~The root cause isn't immediately obvious to me... or it's in plain sight but I'm just not seeing it. Either way, a quick fix is to switch back to the `mpg123` decoder for now, which is what I'll probably do.~~

Edit 2: the issue was actually very obvious -- channel count wasn't being propagated properly from the decoder plugin back to the audio engine. 

This will be fixed in the next release.

**Comment by clangen** [comment] 2017-07-29 23:43
Should be fixed in release 0.22.0, here: https://github.com/clangen/musikcube/releases/tag/0.22.0

**Closed as completed by clangen** 2017-07-29 23:43 UTC
Labels: bug, fixed for next release

**Comment by crstin** [comment] 2017-07-30 01:59
Thanks! All Files work perfectly. I absolutely love this player. Next up: I'd like to add a color theme when I find the time for it.

**Comment by osaatcioglu** [comment] 2017-07-30 10:23
It is working for me too. Thanks for the good work. :)
