### ISSUE TITLE
[REQUEST] Take info accents SEARCH FIELD

### ISSUE THREAD

**Issue by githubdevuser** [clangen/musikcube#366] opened 2020-08-18 13:54 UTC
Can not write and find songs with accents like é,è etc...
Normal or bug?

If I have a title like "dérisoire", I can't even type the "é" in the search tracks interface?

Musikcube is a great software !

**Comment by githubdevuser** [comment] 2020-08-18 14:35
I found that the request exists already, how can I delete my first message?

https://github.com/clangen/musikcube/issues/199

**Comment by clangen** [comment] 2020-08-30 20:45
This ended up being more difficult than I had originally thought. It's still on my radar and I'm trying to find a clean solution that's sufficiently performant. Closing as a duplicate of https://github.com/clangen/musikcube/issues/199

**Closed as completed by clangen** 2020-08-30 20:45 UTC

**Comment by clangen** [comment] 2020-11-14 20:59
Part of 0.95.0, which was just released.
