### ISSUE TITLE
connect to streaming server from desktop client? (like musikdroid but on a pc) 

### ISSUE THREAD

**Issue by misaalanshori** [clangen/musikcube#263] opened 2019-06-23 03:42 UTC
There should be a way to connect to a Musikcube server from the Musikcube desktop client.
Or are there already a way to do this?

**Comment by misaalanshori** [comment] 2019-07-22 11:40
or maybe a web browser client? or has this been talked before?

**Comment by clangen** [comment] 2019-08-29 03:35
Yeah, there's a long history behind the inability to stream from server -> desktop client. The tl;dr is that it's definitely possible but it'll require a fair amount of work. I'm hoping to support it in the future, likely as one of the next major features, once I have time to work on it.

I also started prototyping a web client about a year and a half ago, but didn't get very far (mostly because I don't personally have a need for it). If you're interested, the code is here: https://bitbucket.org/clangen/musikcube-react/src/master/

**Comment by clangen** [comment] 2020-01-06 07:54
Resolving as a duplicate of https://github.com/clangen/musikcube/issues/204

**Closed as completed by clangen** 2020-01-06 07:54 UTC
