### ISSUE TITLE
[request] browse mode - directory + bugs

### ISSUE THREAD

**Issue by pcapiod** [clangen/musikcube#327] opened 2020-03-25 17:33 UTC
Hi,
I have been using your software, and I love the design and the flow in it. I have some request to improve it further : 
- in Browse - directory (shortcut d), we cannot M+ENTER to enter the context menu from the left column.
This mode is not part of the browse tab, so when we are in Browse - directory and if I press b, it goes back to browse mode with artist/album/genres... view. I am not sure if this is intended or not.
When in Browse, it cannot display the Directory tab by pressing 6 to select the categories.

- in KDE, (KDE Neon), the info display from the taskbar does not work properly.
![tmux+musickube_kde](https://user-images.githubusercontent.com/62664084/77565964-485eb380-6ec5-11ea-8096-85f9774c16a8.png)

- in tmux + Konsole (ncurses 6.1), if I go to key bindings tab (?) from the play queue tab (n) and go back to library view (a) (so I go back to the play queue tab), there is some glitch in the display.
![tmux+musickube](https://user-images.githubusercontent.com/62664084/77565961-472d8680-6ec5-11ea-932b-b1ea068339cc.png)

Keep up the good work ! Thanks again

**Comment by clangen** [comment] 2020-04-01 02:45
Sorry, finally getting around to triaging this -- there's a bunch to unpack here. :)

1. I've pushed fix for the two directory browse issues you mentioned.
2. I'll see if I can get a VM up and running with KDE to see if I can figure out how to fix this issue -- I'm not sure where KDE is sourcing this information.
3. This is strange, do all instances of the transport at the bottom seem to work properly? I'm trying to figure out if it's a redraw bug or the controls are actually getting created multiple times.

**Comment by clangen** [comment] 2020-04-01 02:49
I actually may have an idea about the media player issue -- can you tell me which distribution you're using and how you installed musikcube? (i.e. was it install from a package or built from source?).

**Comment by pcapiod** [comment] 2020-04-01 07:43
Hi,
3. Only the bottom one is working, this is only a display matter. It seems that the play queue window height is changing when going back and forth from the shortcuts to the play queue. it is doing max 4 times, each iteration producing an additional bottom bar on top of the previous one.
EDIT : I have tested in Konsole without tmux, and the issue is not there. It seems that this issue occurs only with tmux.

I am using KDE neon (Ubuntu 18.04, KDE plasma 5.18.3). I have installed the software from the deb package.
I have tried to compile it from source, I had a problem at the cmake init with the mpris plugin not being found ([mpris] systemd *not* found. MPRIS plugin not enabled). 
EDIT 2 : Nevermind I could compile it.

**Comment by pcapiod** [comment] 2020-04-01 08:40
Few more ideas I had : 
- In the context menu, it could be nice to have a "hot swap" selection like when hitting M-a. The hot swap does not work from the left column (whatever the category). It does not work as well in the right column when we select the folder name (album name)

- minor thing, when we do from Directory > Play Queue window > Directory, the selection is reset (goes back to the first directory at the top of the list) while in Browse Window (Artists, Albums, Genres...) it does stay on the previous selection.

From the last git version : 
- Not sure if you have finalized the integration of the Directory mode in the Browse Window but when selecting Directory mode via 6, doing something else (going to Play Queue, filter, tracks...) and going back to the Browse Window reset the view to the first selection (Artists). It does not stay on Directory mode but goes back to the previous panel.

If you need more info, please let me know ! 
Again, love your work !

**Comment by clangen** [comment] 2020-04-02 05:50
OK so:

1. I have a feeling your KDE tray icon issues are due to the MPRIS plugin not getting loaded. Do you know if it's working on your installation? If you go to `settings` > `configure plugins` in the app and you don't see `MPRIS interface` it's not working.
2. As you've probably noticed by now, browsing by directory is sort of a special snowflake in that it it's a weird pseudo-category that doesn't behave like the rest. I also don't use it much personally so there are bugs. I just fixed the one where it gets reset when swapping between other views, like the play queue. :)
3. Let me think a bit about the hotswap from the category/directory context menu and get back to you.

Thanks for the feedback and bug reports, they are very helpful!

**Comment by clangen** [comment] 2020-04-03 05:09
Alright, pushed a change that adds hotswap from category/directory list context menu.

**Comment by pcapiod** [comment] 2020-04-03 09:36
> Alright, pushed a change that adds hotswap from category/directory list context menu.

Thanks a lot !

> I have a feeling your KDE tray icon issues are due to the MPRIS plugin not getting loaded. Do you know if it's working on your installation? If you go to settings > configure plugins in the app and you don't see MPRIS interface it's not working.

Indeed, I don't have MPRIS in the plugin list.

> As you've probably noticed by now, browsing by directory is sort of a special snowflake in that it it's a weird pseudo-category that doesn't behave like the rest. I also don't use it much personally so there are bugs. I just fixed the one where it gets reset when swapping between other views, like the play queue. :)

I am, on the contrary, using a lot the directory mode ! The last changes you made are perfect.
If I am thinking of something else, I will let you know. Thanks a lot for listening to my requests ! :+1:

**Comment by clangen** [comment] 2020-04-03 19:07
Awesome, sounds like we're getting close to resolving all of your issues. Sounds like you're building from source now -- if you install `libsystemd-dev` and rebuild like this:

1. `cd ~/src/musikcube` or whatever...
2. `./clean-nix.sh`
3. `cmake .`
4. `make -j4`

It should now enable the MPRIS plugin and the KDE sys tray applet thing should hopefully work properly. If you get around to doing this, let me know if it solves your issue.

As for the `tmux` problem: I'll try to find some time to reproduce the issue this weekend or shortly after -- it'd be nice to fix that as well.

**Comment by pcapiod** [comment] 2020-04-04 08:05
> Awesome, sounds like we're getting close to resolving all of your issues. Sounds like you're building from source now -- if you install libsystemd-dev and rebuild like this:

Indeed, it could find MPRIS and I can modify and play/pause from the task bar. Though it do not detect the song's name and artist and do not display the cover (I suspect KDE to malfunction in this case because I had the same issue with cmus and cmusd).

> As for the tmux problem: I'll try to find some time to reproduce the issue this weekend or shortly after -- it'd be nice to fix that as well.

I tested with a different terminal than Konsole (kitty), the behaviour is the same in tmux.

I have a question, maybe I missed it, is there any way to start globally the playback with a shortcut ? I know it is possible to pause/resume.

EDIT : Ok, actually I can pause but I cannot resume from the taskbar in KDE.

**Comment by clangen** [comment] 2020-04-05 03:09
Alright, I think I got to the bottom of the MPRIS issue.

![image](https://user-images.githubusercontent.com/2031666/78465893-09dcac00-76b0-11ea-9203-0a17072b5db8.png)

Pushed the relevant changes back to `master`.

I tried briefly to repro the tmux issue but haven't been able to so far. I'm going to give it another go tonight if I can find a bit more time.

**Comment by clangen** [comment] 2020-04-05 05:54
Alright, regarding the tmux issue: I tried again on a Ubuntu 18.04 VM with the KDE DE using Konsole and tmux. I did the following:

1. Built musikcube from source.
2. Started a new `tmux` session, started `musikcube`, then added some music.
3. Started playback, switched to the `play queue`
4. Pressed `?` to enter the key bindings screen
5. Pressed `a` to switch back to library > `play queue`
6. Pressed `?` then `a` a few more times. Didn't see the playback controls stack up like your screenshot.

Am I missing a step somewhere? :)

**Comment by pcapiod** [comment] 2020-04-05 14:21
> Alright, regarding the tmux issue: I tried again on a Ubuntu 18.04 VM with the KDE DE using Konsole and tmux. I did the following:
> 
> 1. Built musikcube from source.
> 2. Started a new `tmux` session, started `musikcube`, then added some music.
> 3. Started playback, switched to the `play queue`
> 4. Pressed `?` to enter the key bindings screen
> 5. Pressed `a` to switch back to library > `play queue`
> 6. Pressed `?` then `a` a few more times. Didn't see the playback controls stack up like your screenshot.
> 
> Am I missing a step somewhere? :)

It is the good sequence. Here it is glitching. This is interesting... My tmux config is based on this one : https://github.com/gpakosz/.tmux
Maybe is it the status line with powerline symbols ?

For the MPRIS, everything is working fine now, thanks ! I don't see the cover though (it was doing the same with cmus...). It is not really important to me but I wanted to point it out.

**Comment by clangen** [comment] 2020-04-07 02:30
Yeah, in this case album art will only show up in the little player widget if it's already embedded in the audio file itself as metadata.

I tried that tmux config and enabled the powerline characters, but still wasn't able to repro. :(

**Comment by clangen** [comment] 2020-04-12 05:24
Fixed as part of 0.90.0

**Closed as completed by clangen** 2020-04-12 05:24 UTC
Labels: fixed for next release, linux
