### ISSUE TITLE
No CUE Support

### ISSUE THREAD

**Issue by mabushey** [clangen/musikcube#144] opened 2017-08-01 05:34 UTC
Musikcube does not seem to support single file FLAC's with CUE sheets. Any chance it will be added? I like that it works on a PI and has an Android app. I also like how it lists multiple versions under the title, for instance I have 4 different versions of Megadeth Peace Sells (Original, 2004 re-master, 2011 25th Anniversary, DVD-A). I guess it does that because it doesn't know what to make of CD image Flacs. It doesn't recognize the DVD-A .iso version.

**Comment by Sixardyh** [comment] 2018-05-23 20:50
Any news on this ? This could be a very useful feature.

**Comment by clangen** [comment] 2021-01-28 03:34
Duplicate of https://github.com/clangen/musikcube/issues/390, which has more commentary.

**Closed as completed by clangen** 2021-01-28 03:34 UTC
Labels: feature request, audio format
