### ISSUE TITLE
Segfault on indexing music directory

### ISSUE THREAD

**Issue by msikma** [clangen/musikcube#117] opened 2017-07-26 14:36 UTC
Trying Musikcube for the first time. I added my music directory, which contains a large number of files. Almost immediately while indexing, the program segfaults.

Unfortunately I can't see which file is causing the problem. Presumably there's some specific file there that's crashing the program on ID tag scanning. Any way I can figure out which one it is without removing files from my library one by one until I find the correct one?

<img width="1184" alt="screen shot 2017-07-26 at 16 32 44" src="https://user-images.githubusercontent.com/1507745/28626817-5e6b52e0-7220-11e7-9d24-aa9c060fdcb9.png">

This is on Mac OS X 10.12.5, using a build from Homebrew. I haven't tested the binaries listed here.

Edit: [crash log.](https://gist.github.com/msikma/c44b94263120ddc509e0b93708ca43c5)

**Comment by urspx** [comment] 2017-07-26 15:26
Same issue for me:
`/usr/local/bin/musikcube: line 5: 34687 Segmentation fault: 11  ./musikcube`
while
`syncing metadata (4515 tracks processed)`

**Comment by msikma** [comment] 2017-07-26 20:11
I went ahead and did a binary search (just removing half of my music until I was able to find the file that's causing the problem) and it turned out to be a Captain Beefheart song. Leave it to his crazy music to crash my music player.

I tried to figure out what's different about this specific file (which I can send to you off the record strictly for testing purposes if you want; ask me on [Twitter](https://twitter.com/michielsikma)). As it turns out, it worked again after I opened and saved it using Mp3tag. So I suspect that the ID tags were messed up somehow, causing it to crash. I can provide you with a working and non-working version of the file, which are otherwise identical.

After fixing the file and placing the rest of my music library back, it simply crashed a little further in while scanning a different file. So I think some code in the ID tags scanner needs a little more battle testing.

**Comment by flaviocopes** [comment] 2017-07-26 20:37
Same here, on OSX. Crash log nearly identical to @msikma, can post if needed.

**Comment by msikma** [comment] 2017-07-26 22:13
@flaviocopes @urspx are you using the brew version or a build from the releases page?

**Comment by urspx** [comment] 2017-07-26 22:16
I'm using the brew version on mac OS 10.12.5 (16F73).

Also, as background information - I fed it my iTunes Music folder (just the music folder, nothing else) – I'll try it on some other music folders, too.

**Comment by clangen** [comment] 2017-07-27 03:09
ID3 tag parsing is notoriously difficult and error-prone. The comment earlier in this thread absolutely correct -- the parsing needs to be hardened. 

@msikma I'll reach out to you sometime later this evening on Twitter so I can get my hands on a file that's causing issues. Thanks for offering!

**Comment by christianromney** [comment] 2017-07-27 13:32
Also seeing this. Perhaps this can help: https://gist.github.com/christianromney/c246a3adfa0a13749a0c588f26b5ae24

**Comment by flaviocopes** [comment] 2017-07-27 14:49
@clangen I used a build from the releases page.

**Comment by clangen** [comment] 2017-07-29 02:31
I took at look at @msikma's file that was causing issues, and it was caused by a bug that was already fixed, here: https://github.com/clangen/musikcube/pull/121. I'm going to resolve this issue once we have a new release (hopefully tonight or tomorrow).

**Comment by clangen** [comment] 2017-07-29 23:42
OK, the fix has been released in version 0.22.0 here: https://github.com/clangen/musikcube/releases/tag/0.22.0

Please give this build ago, and re-open this ticket if you still have problems!

**Closed as completed by clangen** 2017-07-29 23:42 UTC
Labels: fixed for next release

**Comment by flaviocopes** [comment] 2017-07-30 07:14
Fixed, thanks!  🙌

**Comment by msikma** [comment] 2017-07-30 11:14
Fed it approximately 70,000 music files, no crash! Thanks. 😄
